### ISSUE TITLE
An illegal memory access was encountered

### ISSUE THREAD

**Issue by qq704554563** [PRBonn/LiDiff#13]
First, i want to express my gratitude for the excellent work you're doing. I've encountered an issue during the training of my network that I hope you can assist with. The details of the error are as follows:
```
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
[KeOps] error: cuMemFree(buffer) failed with error CUDA_ERROR_ILLEGAL_ADDRESS
```
I found that the error occurred during the backward pass of the `MinkGlobalEnc` module. Could you please provide some guidance on how to resolve this issue?

Thank you very much for your help!

**Comment by nuneslu** [comment]
Hi! This is a strange error, seems to be related to the pykeops library. Can you share which GPU are you using? And are you using the same pykeops version as in the requirements?

**Comment by qq704554563** [comment]
Thank you for the reply.
I have installed the required version and tested the code on both RTX 3090 and A100 GPUs. The CUDA version used is 11.1.

**Comment by nuneslu** [comment]
I would suggest to uninstall pykeops and install it again without an specificied version, just with “pip3 install pykeops”

**Comment by qq704554563** [comment]
Thank you for the helpful suggestion! I have reinstalled all the packages and resolved the error. It seems that the error was induced by MinkowskiEngine.
By the way, is it normal for the training speed to be 4-5s/it?

**Comment by nuneslu** [comment]
Glad to hear that! The iteration time depends on the setup, for it was around 3s per iteration, so I guess it is within the same time.

**Comment by qq704554563** [comment]
Sorry to bother you again. My distributed training with 2 GPUs works fine, but when I use more than 3 GPUs, it throws an error.
`RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.`

**Comment by qq704554563** [comment]
Problem Solved: I use --ipc=host in my docker.
